name: Build and deploy an app to AKS with Helm

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  RESOURCE_GROUP: "azurehelm"
  CHART_PATH: "./manifests/charts/default/"
  CHART_OVERRIDE_PATH: "./manifests/charts/default/values.yaml"
  CLUSTER_NAME: "kube1"
  NAMESPACE: "istio-system"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
 
    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v2.0
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }} 
    # Runs Helm to create manifest files
    - name: Bake deployment
      uses: azure/k8s-bake@v2.1
      with:
        renderEngine: 'helm'
        helmChart: ${{ env.CHART_PATH }}
        overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}
        helm-version: 'latest' 
      id: bake
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -
    - name: Azure deploy  
      uses: Azure/k8s-deploy@v1
      with:
        namespace: ${{ env.NAMESPACE }}
        manifests: ${{ steps.bake.outputs.manifestsBundle }}